"""add rag tables

Revision ID: 843141d56b2e
Revises: aec067cfaffe
Create Date: 2026-06-09 15:46:01.387370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '843141d56b2e'
down_revision: Union[str, Sequence[str], None] = 'aec067cfaffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_clients',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index('idx_rag_clients_client_id', 'rag_clients', ['client_id'], unique=False)
    op.create_index('idx_rag_clients_is_active', 'rag_clients', ['is_active'], unique=False)
    op.create_table('rag_conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('corpus_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index('idx_rag_conversations_client_id', 'rag_conversations', ['client_id'], unique=False)
    op.create_index('idx_rag_conversations_conversation_id', 'rag_conversations', ['conversation_id'], unique=False)
    op.create_index('idx_rag_conversations_corpus_id', 'rag_conversations', ['corpus_id'], unique=False)
    op.create_index('idx_rag_conversations_created_at', 'rag_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_conversations_id'), 'rag_conversations', ['id'], unique=False)
    op.create_table('rag_corpora',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('corpus_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'corpus_id', name='uq_rag_corpora_client_corpus')
    )
    op.create_index('idx_rag_corpora_client_id', 'rag_corpora', ['client_id'], unique=False)
    op.create_index('idx_rag_corpora_corpus_id', 'rag_corpora', ['corpus_id'], unique=False)
    op.create_index('idx_rag_corpora_is_active', 'rag_corpora', ['is_active'], unique=False)
    op.create_table('rag_ingestion_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('corpus_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_sources', sa.BigInteger(), nullable=False),
    sa.Column('processed_sources', sa.BigInteger(), nullable=False),
    sa.Column('failed_sources', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('idx_rag_ingestion_jobs_client_id', 'rag_ingestion_jobs', ['client_id'], unique=False)
    op.create_index('idx_rag_ingestion_jobs_corpus_id', 'rag_ingestion_jobs', ['corpus_id'], unique=False)
    op.create_index('idx_rag_ingestion_jobs_job_id', 'rag_ingestion_jobs', ['job_id'], unique=False)
    op.create_index('idx_rag_ingestion_jobs_job_type', 'rag_ingestion_jobs', ['job_type'], unique=False)
    op.create_index('idx_rag_ingestion_jobs_source_id', 'rag_ingestion_jobs', ['source_id'], unique=False)
    op.create_index('idx_rag_ingestion_jobs_status', 'rag_ingestion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_rag_ingestion_jobs_id'), 'rag_ingestion_jobs', ['id'], unique=False)
    op.create_table('rag_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_messages_conversation_id', 'rag_messages', ['conversation_id'], unique=False)
    op.create_index('idx_rag_messages_created_at', 'rag_messages', ['created_at'], unique=False)
    op.create_index('idx_rag_messages_role', 'rag_messages', ['role'], unique=False)
    op.create_index(op.f('ix_rag_messages_id'), 'rag_messages', ['id'], unique=False)
    op.create_table('rag_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('corpus_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('qdrant_points_count', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index('idx_rag_sources_client_id', 'rag_sources', ['client_id'], unique=False)
    op.create_index('idx_rag_sources_content_hash', 'rag_sources', ['content_hash'], unique=False)
    op.create_index('idx_rag_sources_corpus_id', 'rag_sources', ['corpus_id'], unique=False)
    op.create_index('idx_rag_sources_created_at', 'rag_sources', ['created_at'], unique=False)
    op.create_index('idx_rag_sources_source_id', 'rag_sources', ['source_id'], unique=False)
    op.create_index('idx_rag_sources_source_type', 'rag_sources', ['source_type'], unique=False)
    op.create_index('idx_rag_sources_status', 'rag_sources', ['status'], unique=False)
    op.create_index(op.f('ix_rag_sources_id'), 'rag_sources', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_sources_id'), table_name='rag_sources')
    op.drop_index('idx_rag_sources_status', table_name='rag_sources')
    op.drop_index('idx_rag_sources_source_type', table_name='rag_sources')
    op.drop_index('idx_rag_sources_source_id', table_name='rag_sources')
    op.drop_index('idx_rag_sources_created_at', table_name='rag_sources')
    op.drop_index('idx_rag_sources_corpus_id', table_name='rag_sources')
    op.drop_index('idx_rag_sources_content_hash', table_name='rag_sources')
    op.drop_index('idx_rag_sources_client_id', table_name='rag_sources')
    op.drop_table('rag_sources')
    op.drop_index(op.f('ix_rag_messages_id'), table_name='rag_messages')
    op.drop_index('idx_rag_messages_role', table_name='rag_messages')
    op.drop_index('idx_rag_messages_created_at', table_name='rag_messages')
    op.drop_index('idx_rag_messages_conversation_id', table_name='rag_messages')
    op.drop_table('rag_messages')
    op.drop_index(op.f('ix_rag_ingestion_jobs_id'), table_name='rag_ingestion_jobs')
    op.drop_index('idx_rag_ingestion_jobs_status', table_name='rag_ingestion_jobs')
    op.drop_index('idx_rag_ingestion_jobs_source_id', table_name='rag_ingestion_jobs')
    op.drop_index('idx_rag_ingestion_jobs_job_type', table_name='rag_ingestion_jobs')
    op.drop_index('idx_rag_ingestion_jobs_job_id', table_name='rag_ingestion_jobs')
    op.drop_index('idx_rag_ingestion_jobs_corpus_id', table_name='rag_ingestion_jobs')
    op.drop_index('idx_rag_ingestion_jobs_client_id', table_name='rag_ingestion_jobs')
    op.drop_table('rag_ingestion_jobs')
    op.drop_index('idx_rag_corpora_is_active', table_name='rag_corpora')
    op.drop_index('idx_rag_corpora_corpus_id', table_name='rag_corpora')
    op.drop_index('idx_rag_corpora_client_id', table_name='rag_corpora')
    op.drop_table('rag_corpora')
    op.drop_index(op.f('ix_rag_conversations_id'), table_name='rag_conversations')
    op.drop_index('idx_rag_conversations_created_at', table_name='rag_conversations')
    op.drop_index('idx_rag_conversations_corpus_id', table_name='rag_conversations')
    op.drop_index('idx_rag_conversations_conversation_id', table_name='rag_conversations')
    op.drop_index('idx_rag_conversations_client_id', table_name='rag_conversations')
    op.drop_table('rag_conversations')
    op.drop_index('idx_rag_clients_is_active', table_name='rag_clients')
    op.drop_index('idx_rag_clients_client_id', table_name='rag_clients')
    op.drop_table('rag_clients')
    # ### end Alembic commands ###
