"""init clean schema

Revision ID: 906c33095bc3
Revises: 
Create Date: 2026-03-26 22:04:00.967681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '906c33095bc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('project', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('feature', sa.Text(), nullable=False),
    sa.Column('model_requested', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('messages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('finish_reason', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('pipeline_name', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_interactions_client_created_at', 'ai_interactions', ['client_id', 'created_at'], unique=False)
    op.create_index('idx_ai_interactions_client_id', 'ai_interactions', ['client_id'], unique=False)
    op.create_index('idx_ai_interactions_created_at', 'ai_interactions', ['created_at'], unique=False)
    op.create_index('idx_ai_interactions_feature', 'ai_interactions', ['feature'], unique=False)
    op.create_index('idx_ai_interactions_project', 'ai_interactions', ['project'], unique=False)
    op.create_index('idx_ai_interactions_project_created_at', 'ai_interactions', ['project', 'created_at'], unique=False)
    op.create_index('idx_ai_interactions_request_id', 'ai_interactions', ['request_id'], unique=False)
    op.create_index('idx_ai_interactions_status_code', 'ai_interactions', ['status_code'], unique=False)
    op.create_index(op.f('ix_ai_interactions_id'), 'ai_interactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_interactions_id'), table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_status_code', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_request_id', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_project_created_at', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_project', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_feature', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_created_at', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_client_id', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_client_created_at', table_name='ai_interactions')
    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
