"""add original fields to point feedback

Revision ID: 9414697736ca
Revises: e5eb8542bf99
Create Date: 2026-04-14 13:16:26.640470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9414697736ca'
down_revision: Union[str, Sequence[str], None] = 'e5eb8542bf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_feedback', sa.Column('original_text', sa.Text(), nullable=True))
    op.add_column('point_feedback', sa.Column('original_sentiment', sa.Integer(), nullable=True))
    op.add_column('point_feedback', sa.Column('original_category', sa.Text(), nullable=True))
    op.drop_column('point_feedback', 'corrected_sentiment')
    op.add_column('point_feedback', sa.Column('corrected_sentiment', sa.Integer(), nullable=True))
    op.create_index('idx_response_points_sentiment', 'response_points', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_response_points_sentiment', table_name='response_points')
    op.drop_column('point_feedback', 'corrected_sentiment')
    op.add_column('point_feedback', sa.Column('corrected_sentiment', sa.Text(), nullable=True))
    op.drop_column('point_feedback', 'original_category')
    op.drop_column('point_feedback', 'original_sentiment')
    op.drop_column('point_feedback', 'original_text')
    # ### end Alembic commands ###
