"""add survey tables

Revision ID: a74bd4e99573
Revises: 906c33095bc3
Create Date: 2026-03-26 22:19:26.308504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a74bd4e99573'
down_revision: Union[str, Sequence[str], None] = '906c33095bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_id', sa.Text(), nullable=False),
    sa.Column('point_id', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('corrected_sentiment', sa.Text(), nullable=True),
    sa.Column('corrected_category', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_point_feedback_created_at', 'point_feedback', ['created_at'], unique=False)
    op.create_index('idx_point_feedback_point_id', 'point_feedback', ['point_id'], unique=False)
    op.create_index('idx_point_feedback_response_id', 'point_feedback', ['response_id'], unique=False)
    op.create_index(op.f('ix_point_feedback_id'), 'point_feedback', ['id'], unique=False)
    op.create_table('response_points',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('point_id', sa.Text(), nullable=False),
    sa.Column('response_id', sa.Text(), nullable=False),
    sa.Column('point_text', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Text(), nullable=False),
    sa.Column('pipeline_name', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_id')
    )
    op.create_index('idx_response_points_category', 'response_points', ['category'], unique=False)
    op.create_index('idx_response_points_created_at', 'response_points', ['created_at'], unique=False)
    op.create_index('idx_response_points_point_id', 'response_points', ['point_id'], unique=False)
    op.create_index('idx_response_points_response_id', 'response_points', ['response_id'], unique=False)
    op.create_index('idx_response_points_sentiment', 'response_points', ['sentiment'], unique=False)
    op.create_index(op.f('ix_response_points_id'), 'response_points', ['id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('survey_id', sa.Text(), nullable=False),
    sa.Column('question_id', sa.Text(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('response_id', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pipeline_name', sa.Text(), nullable=True),
    sa.Column('pipeline_version', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_index('idx_survey_responses_created_at', 'survey_responses', ['created_at'], unique=False)
    op.create_index('idx_survey_responses_question_id', 'survey_responses', ['question_id'], unique=False)
    op.create_index('idx_survey_responses_response_id', 'survey_responses', ['response_id'], unique=False)
    op.create_index('idx_survey_responses_survey_id', 'survey_responses', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_id'), 'survey_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_id'), table_name='survey_responses')
    op.drop_index('idx_survey_responses_survey_id', table_name='survey_responses')
    op.drop_index('idx_survey_responses_response_id', table_name='survey_responses')
    op.drop_index('idx_survey_responses_question_id', table_name='survey_responses')
    op.drop_index('idx_survey_responses_created_at', table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_response_points_id'), table_name='response_points')
    op.drop_index('idx_response_points_sentiment', table_name='response_points')
    op.drop_index('idx_response_points_response_id', table_name='response_points')
    op.drop_index('idx_response_points_point_id', table_name='response_points')
    op.drop_index('idx_response_points_created_at', table_name='response_points')
    op.drop_index('idx_response_points_category', table_name='response_points')
    op.drop_table('response_points')
    op.drop_index(op.f('ix_point_feedback_id'), table_name='point_feedback')
    op.drop_index('idx_point_feedback_response_id', table_name='point_feedback')
    op.drop_index('idx_point_feedback_point_id', table_name='point_feedback')
    op.drop_index('idx_point_feedback_created_at', table_name='point_feedback')
    op.drop_table('point_feedback')
    # ### end Alembic commands ###
