"""add request_id to survey_processing_jobs

Revision ID: aec067cfaffe
Revises: b3b9f0ea420e
Create Date: 2026-04-24 17:36:53.545018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec067cfaffe'
down_revision: Union[str, Sequence[str], None] = 'b3b9f0ea420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_feedback', sa.Column('client_id', sa.Text(), nullable=True))
    op.create_index('idx_point_feedback_client_id', 'point_feedback', ['client_id'], unique=False)
    op.add_column('response_points', sa.Column('client_id', sa.Text(), nullable=True))
    op.create_index('idx_response_points_client_id', 'response_points', ['client_id'], unique=False)
    op.add_column('survey_processing_jobs', sa.Column('request_id', sa.Text(), nullable=True))
    op.create_index('idx_survey_processing_jobs_request_id', 'survey_processing_jobs', ['request_id'], unique=False)
    op.add_column('survey_responses', sa.Column('client_id', sa.Text(), nullable=True))
    op.create_index('idx_survey_responses_client_id', 'survey_responses', ['client_id'], unique=False)
    op.add_column('validated_response_points', sa.Column('client_id', sa.Text(), nullable=True))
    op.create_index('idx_vrp_client_id', 'validated_response_points', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vrp_client_id', table_name='validated_response_points')
    op.drop_column('validated_response_points', 'client_id')
    op.drop_index('idx_survey_responses_client_id', table_name='survey_responses')
    op.drop_column('survey_responses', 'client_id')
    op.drop_index('idx_survey_processing_jobs_request_id', table_name='survey_processing_jobs')
    op.drop_column('survey_processing_jobs', 'request_id')
    op.drop_index('idx_response_points_client_id', table_name='response_points')
    op.drop_column('response_points', 'client_id')
    op.drop_index('idx_point_feedback_client_id', table_name='point_feedback')
    op.drop_column('point_feedback', 'client_id')
    # ### end Alembic commands ###
