"""add validated response points

Revision ID: b3b9f0ea420e
Revises: 9414697736ca
Create Date: 2026-04-14 14:50:07.729028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b9f0ea420e'
down_revision: Union[str, Sequence[str], None] = '9414697736ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validated_response_points',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('response_id', sa.Text(), nullable=False),
    sa.Column('point_id', sa.Text(), nullable=True),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('final_sentiment', sa.Integer(), nullable=True),
    sa.Column('final_category', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Text(), nullable=False),
    sa.Column('operator_id', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vrp_category', 'validated_response_points', ['final_category'], unique=False)
    op.create_index('idx_vrp_created_at', 'validated_response_points', ['created_at'], unique=False)
    op.create_index('idx_vrp_point_id', 'validated_response_points', ['point_id'], unique=False)
    op.create_index('idx_vrp_response_id', 'validated_response_points', ['response_id'], unique=False)
    op.create_index('idx_vrp_sentiment', 'validated_response_points', ['final_sentiment'], unique=False)
    op.create_index(op.f('ix_validated_response_points_id'), 'validated_response_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validated_response_points_id'), table_name='validated_response_points')
    op.drop_index('idx_vrp_sentiment', table_name='validated_response_points')
    op.drop_index('idx_vrp_response_id', table_name='validated_response_points')
    op.drop_index('idx_vrp_point_id', table_name='validated_response_points')
    op.drop_index('idx_vrp_created_at', table_name='validated_response_points')
    op.drop_index('idx_vrp_category', table_name='validated_response_points')
    op.drop_table('validated_response_points')
    # ### end Alembic commands ###
