"""add ai_interactions indexes

Revision ID: ce5656a45357
Revises: b0f479307ed7
Create Date: 2026-03-26 17:25:26.112127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5656a45357'
down_revision: Union[str, Sequence[str], None] = 'b0f479307ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ai_interactions_client_created_at', 'ai_interactions', ['client_id', 'created_at'], unique=False)
    op.create_index('idx_ai_interactions_client_id', 'ai_interactions', ['client_id'], unique=False)
    op.create_index('idx_ai_interactions_created_at', 'ai_interactions', ['created_at'], unique=False)
    op.create_index('idx_ai_interactions_feature', 'ai_interactions', ['feature'], unique=False)
    op.create_index('idx_ai_interactions_project', 'ai_interactions', ['project'], unique=False)
    op.create_index('idx_ai_interactions_project_created_at', 'ai_interactions', ['project', 'created_at'], unique=False)
    op.create_index('idx_ai_interactions_request_id', 'ai_interactions', ['request_id'], unique=False)
    op.create_index('idx_ai_interactions_status_code', 'ai_interactions', ['status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_interactions_status_code', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_request_id', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_project_created_at', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_project', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_feature', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_created_at', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_client_id', table_name='ai_interactions')
    op.drop_index('idx_ai_interactions_client_created_at', table_name='ai_interactions')
    # ### end Alembic commands ###
