"""clean survey refactor

Revision ID: e5eb8542bf99
Revises: a74bd4e99573
Create Date: 2026-04-13 20:22:49.063103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5eb8542bf99'
down_revision: Union[str, Sequence[str], None] = 'a74bd4e99573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_processing_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_id', sa.Text(), nullable=False),
    sa.Column('survey_id', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('request_payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_id')
    )
    op.create_index('idx_survey_processing_jobs_client_id', 'survey_processing_jobs', ['client_id'], unique=False)
    op.create_index('idx_survey_processing_jobs_created_at', 'survey_processing_jobs', ['created_at'], unique=False)
    op.create_index('idx_survey_processing_jobs_processing_id', 'survey_processing_jobs', ['processing_id'], unique=False)
    op.create_index('idx_survey_processing_jobs_status', 'survey_processing_jobs', ['status'], unique=False)
    op.create_index('idx_survey_processing_jobs_survey_id', 'survey_processing_jobs', ['survey_id'], unique=False)
    op.create_index(op.f('ix_survey_processing_jobs_id'), 'survey_processing_jobs', ['id'], unique=False)
    op.drop_column('response_points', 'sentiment')
    op.add_column('response_points', sa.Column('sentiment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response_points', 'sentiment')
    op.add_column('response_points', sa.Column('sentiment', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_survey_processing_jobs_id'), table_name='survey_processing_jobs')
    op.drop_index('idx_survey_processing_jobs_survey_id', table_name='survey_processing_jobs')
    op.drop_index('idx_survey_processing_jobs_status', table_name='survey_processing_jobs')
    op.drop_index('idx_survey_processing_jobs_processing_id', table_name='survey_processing_jobs')
    op.drop_index('idx_survey_processing_jobs_created_at', table_name='survey_processing_jobs')
    op.drop_index('idx_survey_processing_jobs_client_id', table_name='survey_processing_jobs')
    op.drop_table('survey_processing_jobs')
    # ### end Alembic commands ###
